name: extended_text
description: Extended official text to build special text like inline image or @somebody quickly,it also support custom background,custom over flow and custom selection toolbar and handles.
version: 10.0.0-dev
homepage: https://github.com/fluttercandies/extended_text

environment:
  sdk: '>=2.18.0-36.0.dev <3.0.0'
  flutter: ">=2.10.0"

dependencies:
  extended_text_library: ^10.0.0-dev
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


